
// CSS STYLES
import '@/styles/globals.css';
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
